export { codeDialect } from "@genui/protocol"
export { action, Genui } from "./registry.js"
export { memoryStore } from "./surface-runtime.js"
export type { CallAuditEntry, GenuiOptions } from "./registry.js"
export type { ExecuteOptions, SurfaceStore } from "./types.js"
